import { TableDefinition } from '../types';

// Canonical ContactsDirectory schema (normalized from AppSheet export).
// Enum fields slice from EnumsCatalog by EnumCategory and display DisplayName.
// Stored value defaults to EnumValue unless enumValueSource is explicitly set to uniqueId/displayName.
export const CONTACTS_DIRECTORY_TABLE_DEF: TableDefinition = {
  id: 'contacts',
  name: 'Contacts Directory',
  keyField: 'id',
  labelField: 'name',
  schema: [
    { name: 'ContactID', label: 'Contact ID', type: 'Text' },

    { name: 'about_break', label: 'About', type: 'PageBreak' },
    { name: 'FirstName', label: 'First Name', type: 'Name' },
    { name: 'LastName', label: 'Last Name', type: 'Name' },
    { name: 'Photo', label: 'Photo', type: 'Image' },
    {
      name: 'EntityKind',
      label: 'Entity Type',
      type: 'Enum',
      enumCategory: 'EntityKind',
      enumValueSource: 'enumValue',
    },
    {
      name: 'ServicesAndProviders',
      label: 'Services & Providers',
      type: 'Enum',
      enumCategory: 'ServicesAndProviders',
      enumValueSource: 'enumValue',
    },
    {
      name: 'ProRoleType',
      label: 'Transaction Services',
      type: 'Enum',
      enumCategory: 'ProRoleType',
      enumValueSource: 'enumValue',
      showIf: "['Broker_Lender_Closing_Services', 'Internal_Members'].includes(data.ServicesAndProviders)",
    },
    {
      name: 'VendorRole',
      label: 'Vendor Services',
      type: 'Enum',
      enumCategory: 'VendorRole',
      enumValueSource: 'enumValue',
      showIf: "['Vendor_Services', 'Internal_Members'].includes(data.ServicesAndProviders) && (ui.viewType === 'Form' || Boolean(data.VendorRole))",
    },
    {
      name: 'BranchCategory',
      label: 'Branch / Category',
      type: 'Enum',
      enumCategory: 'Branch_Category',
      enumValueSource: 'enumValue',
      showIf: "data.ServicesAndProviders === 'Law_Enforcement_Agency'",
    },
    {
      name: 'Job',
      label: 'Job',
      type: 'Enum',
      optionsCategorySourceField: 'BranchCategory',
      enumValueSource: 'enumValue',
      showIf: 'Boolean(data.BranchCategory)',
    },

    { name: 'my_home_break', label: 'My Home', type: 'PageBreak', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'HomePhone', label: 'Home Phone', type: 'Phone', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'HomeAddress', label: 'Home Address', type: 'Address', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'City', label: 'City', type: 'Text', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'County', label: 'County', type: 'Text', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'State', label: 'State', type: 'Enum', enumCategory: 'State', enumValueSource: 'enumValue', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'ZipCode', label: 'Zip Code', type: 'Number', showIf: "data.ServicesAndProviders === 'Clients'" },

    { name: 'contact_info_break', label: 'Contact Info', type: 'PageBreak' },
    { name: 'Mobile', label: 'Mobile', type: 'Phone' },
    { name: 'Email', label: 'Email', type: 'Email' },

    { name: 'professional_break', label: 'Professional Profile', type: 'PageBreak', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'CompanyName', label: 'Company Name', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'Title_Tagline', label: 'Title / Tagline', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'TeamName', label: 'Team Name', type: 'Text', showIf: "data.EntityKind === 'Team'" },
    { name: 'BrokerLicense', label: 'Broker License', type: 'Text', showIf: "['Internal_Members', 'Broker_Lender_Closing_Services', 'Vendor_Services', 'Rental_Building'].includes(data.ServicesAndProviders)" },
    { name: 'ContactLicense', label: 'Contact License', type: 'Text', showIf: "['Internal_Members', 'Broker_Lender_Closing_Services', 'Vendor_Services', 'Rental_Building'].includes(data.ServicesAndProviders)" },
    { name: 'BusinessPhone', label: 'Business Phone', type: 'Phone', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'OfficeEmail', label: 'Office Email', type: 'Email', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'BusinessStreetAddress', label: 'Business Street Address', type: 'Address', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'BusinessCity', label: 'Business City', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'BusinessState', label: 'Business State', type: 'Enum', enumCategory: 'State', enumValueSource: 'enumValue', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },

    { name: 'social_break', label: 'Website & Social', type: 'PageBreak', showIf: "data.ServicesAndProviders !== 'Law_Enforcement_Agency'" },
    { name: 'WebsiteURL', label: 'Website URL', type: 'Url', showIf: "data.ServicesAndProviders !== 'Law_Enforcement_Agency'" },
    { name: 'ProfileURL', label: 'Profile URL', type: 'Url', showIf: "data.ServicesAndProviders !== 'Law_Enforcement_Agency'" },
    { name: 'YouTube', label: 'YouTube', type: 'Url', showIf: "data.ServicesAndProviders !== 'Law_Enforcement_Agency'" },
    { name: 'YouTubeThumbnail', label: 'YouTube Thumbnail', type: 'Image', showIf: "ui.touched.YouTube || ui.activeField === 'YouTube' || Boolean(data.YouTube)" },
    { name: 'YouTubePlayer', label: 'YouTube Player', type: 'App', showIf: 'Boolean(data.YouTube)' },
    { name: 'ShareWith', label: 'Share With', type: 'Email' },
    { name: 'LinkedInURL', label: 'LinkedIn URL', type: 'Url' },
    { name: 'FacebookURL', label: 'Facebook URL', type: 'Url' },
    { name: 'InstagramURL', label: 'Instagram URL', type: 'Url' },
    { name: 'WhatsAppURL', label: 'WhatsApp URL', type: 'Url' },
    { name: 'TikTokURL', label: 'TikTok URL', type: 'Url' },
    { name: 'X_URL', label: 'X URL', type: 'Url' },
    { name: 'OwnerEmail', label: 'Owner Email', type: 'Email' },

    { name: 'notes_break', label: 'Notes', type: 'PageBreak' },
    { name: 'Rating', label: 'Rating', type: 'Enum', enumCategory: 'Rating', enumValueSource: 'enumValue' },
    { name: 'AI_ResponseMode', label: 'AI Response Mode', type: 'Enum', enumCategory: 'AI_ResponseMode', enumValueSource: 'enumValue' },
    { name: 'Tags', label: 'Tags', type: 'EnumList', enumCategory: 'TagList', enumValueSource: 'enumValue' },
    { name: 'AdditionalInfo', label: 'Additional Info', type: 'LongText' },
    { name: 'notes', label: 'Private Notes', type: 'LongText' },

    { name: 'security_break', label: 'Security', type: 'PageBreak', showIf: "data.ServicesAndProviders === 'Internal_Members'" },
    { name: 'SecurityLevel', label: 'Security Level', type: 'Number', showIf: "data.ServicesAndProviders === 'Internal_Members'" },
    { name: 'AddedBy', label: 'Added By', type: 'Email', showIf: "data.ServicesAndProviders === 'Internal_Members'" },
    { name: 'AppUserRef', label: 'App User', type: 'Ref', showIf: "data.ServicesAndProviders === 'Internal_Members'" },
    { name: 'DateAdded', label: 'Date Added', type: 'DateTime', showIf: "data.ServicesAndProviders === 'Internal_Members'" },
    { name: 'TenantID', label: 'Tenant ID', type: 'Text', showIf: "data.ServicesAndProviders === 'Internal_Members'" },

    // Virtual/computed style fields kept hidden for future backend parity.
    { name: 'FullName', label: 'Full Name (Computed)', type: 'Text', hidden: true },
    { name: 'ComputedAddress', label: 'Computed Address', type: 'Address', hidden: true },
    { name: 'Avatar', label: 'Avatar', type: 'Thumbnail', hidden: true },
    { name: 'EntryProfile', label: 'Entry Profile', type: 'Text', hidden: true },
  ],
};

