import { TableDefinition } from '../types';

const ENTITY_KIND_OPTIONS = ['Person', 'Company', 'Team', 'Bot'];

const SERVICES_AND_PROVIDERS_OPTIONS = [
  'Clients',
  'Broker/Lender/Closing Services',
  'Vendor Services',
  'Law Enforcement Agency',
  'Rental Building',
  'Internal Members',
];

const PRO_ROLE_OPTIONS = [
  'Agent',
  'Broker',
  'Leasing Agent',
  'Appraiser',
  'Attorney',
  'Escrow Officer',
  'Loan Officer',
  'Title Officer',
  'Transaction Coordinator',
];

const VENDOR_ROLE_OPTIONS = [
  'Cabinet Maker',
  'Carpenter',
  'Concrete Mason',
  'Contractor',
  'Demolition',
  'Electrician',
  'Flooring',
  'Gardener',
  'Home Warranty',
  'Homeowners Association',
  'House Cleaner',
  'Inspector Pest',
  'Inspector Property',
  'Inspector Roof',
  'Inspector Sewer-Well',
  'Insurance',
  'Interior Designer',
  'Junk Removal',
  'Landscaper',
  'Movers',
  'Notary',
  'Other',
  'Painter',
  'Pest Control',
  'Photographer Videographer',
  'Plumber',
  'Pool Service',
  'Roofer',
  'Signs Install/Removal',
  'Staging Home Service',
  'Tile and Granite Mason',
  'Utilities',
  'Vendor',
];

const BRANCH_CATEGORY_OPTIONS = [
  'Military',
  'Law Enforcement Officers: Municipal/State',
  'Emergency Medical Technicians',
  'Federal Law Enforcement: Dept of Justice (DOJ)',
  'Federal Law Enforcement: Independent Agency',
  'Federal Law Enforcement: Dept of Homeland Security (DHS)',
  'Federal Law Enforcement: Dept of Defense (DoD)',
  'Federal Law Enforcement: Dept of Interior (DOI)',
  'Federal Law Enforcement: Other Depts',
  'Firefighters',
  '911 Dispatchers',
];

const BRANCH_TO_JOB_OPTIONS: Record<string, string[]> = {
  Military: [
    'Air Force',
    'Army',
    'Coast Guard',
    'Marine Corp',
    'Navy',
    'Space Force',
  ],
  'Law Enforcement Officers: Municipal/State': [
    'Animal control officers (LEO credentialed)',
    'Assistant chief officers',
    'Auxiliary & reserve sheriff deputies or police officers',
    'Bridge and tunnel officers',
    'Chief officers',
    'Conservation officers',
    'Correctional supply officers',
    'Corrections officers (government or private)',
    'Emergency response teams (ERT)',
    'Inmate recovery teams (IRT)',
    'Quick response strike teams (QRST)',
    'Special emergency response teams (SERT)',
    'Courthouse security personnel',
    'Detention officers (government or private)',
    'Family court officers',
    'District Attorneys',
    'Fire marshals (LEO certified)',
    'Fleet reserves',
    'Game wardens',
    'Investigators (state or local)',
    'Jailers (government or private)',
    'Jail Administrators / Assistant Jail Administrators',
    'Juvenile institutional officers (peace officers)',
    'Metro transit police',
    'Park rangers (state)',
    'Parole officers',
    'Patrol officers',
    'Patrol deputies',
    'Police officers (federal state local; campus police)',
    'Pretrial services officers',
    'Probation officers',
    'Railroad police officers',
    'School resource officers',
    "Sheriff's deputies",
    "State's attorneys",
    'State capitol police',
    'State law enforcement agents',
    'State troopers',
    'State police inspectors',
    'Tribal police',
    'Wildlife officers',
  ],
  'Emergency Medical Technicians': [
    'Emergency medical technicians (EMTs) - Basic medium or advanced',
    'Flight nurses',
    'Medical helicopter pilots',
    'Mobile intensive care nurses',
    'National Ski Patrol Members',
    'Paramedics',
    'Pre-Hospital Registered Nurses',
    'Transport nurses (ALS Ground/Air Medical ACM-FN)',
  ],
  'Federal Law Enforcement: Dept of Justice (DOJ)': [
    'Alcohol Tobacco & Firearms (ATF) Employees',
    'Drug Enforcement Agency (DEA) Employees',
    'Federal Bureau of Investigations (FBI) Employees',
    'US Marshals Service Personnel',
    'US Attorneys',
    'US Attorneys General',
    'Bureau of Prisons (BOP) Employees',
  ],
  'Federal Law Enforcement: Independent Agency': [
    'Amtrak Police Department Officers',
    'Central Intelligence Agency (CIA) Employees',
    'US Postal Inspectors (and Criminal Investigators)',
  ],
  'Federal Law Enforcement: Dept of Homeland Security (DHS)': [
    'Customs & Border Patrol (CBP) Agents',
    'Immigration and Customs Enforcement (ICE) Agents',
    'Air Marshals',
    'Federal Flight Deck Officers (FFDO)',
    'Federal Protective Service Officers',
    'TSA Agents (Red Shield ONLY)',
    'US Secret Service Agents',
  ],
  'Federal Law Enforcement: Dept of Defense (DoD)': [
    'Air Force Office of Special Investigations Agents',
    'Defense Criminal Investigative Service (DCIS) Agents',
    'Naval Criminal Investigative Service (NCIS) Agents',
  ],
  'Federal Law Enforcement: Dept of Interior (DOI)': [
    'US Park police',
    'US Park rangers',
  ],
  'Federal Law Enforcement: Other Depts': [
    'Dept of Agriculture Office of Inspector General Special Agents',
    'Dept of Corrections Personnel',
    'Dept of Fish and Game Wardens',
    'Dept of Public Safety Officers',
    'Dept of State Agents',
    'Dept of the Treasury Agents',
    'SSA Assistant Special Agents',
    'US Capitol police',
  ],
  Firefighters: [
    'Airport fire operations',
    'Fire Commissioners',
    'Fire Engineers',
    'Fire medical officers',
    'Firefighters - career volunteer and retired (federal included)',
    'Fire marshals',
    'Helitack crews',
    'Fire Lieutenants',
    'Past fire chiefs',
    'Probationary firefighters',
    'Supervisory forestry technicians',
    'Wildland firefighters/ prescribed fire burn managers',
  ],
  '911 Dispatchers': [
    'Fire communications officers',
    'Police or EMS dispatchers',
    'Police compliant officers (911 dispatchers)',
    'Police service representatives (LAPD only)',
    'Public safety telecommunicators (PST)',
  ],
};

export const CONTACTS_DIRECTORY_TABLE_DEF: TableDefinition = {
  id: 'contacts',
  name: 'Contacts Directory',
  keyField: 'id',
  labelField: 'name',
  schema: [
    { name: 'name', label: 'Full Name', type: 'Name' },
    { name: 'FirstName', label: 'First Name', type: 'Name' },
    { name: 'LastName', label: 'Last Name', type: 'Name' },
    { name: 'Photo', label: 'Photo', type: 'Image' },
    {
      name: 'EntityKind',
      label: 'Entity Type',
      type: 'Enum',
      options: ENTITY_KIND_OPTIONS,
    },
    {
      name: 'ServicesAndProviders',
      label: 'Services & Providers',
      type: 'Enum',
      options: SERVICES_AND_PROVIDERS_OPTIONS,
    },
    {
      name: 'ProRoleType',
      label: 'Transaction Services',
      type: 'Enum',
      options: PRO_ROLE_OPTIONS,
      showIf: "['Broker/Lender/Closing Services', 'Internal Members'].includes(data.ServicesAndProviders)",
    },
    {
      name: 'VendorRole',
      label: 'Vendor Services',
      type: 'Enum',
      options: VENDOR_ROLE_OPTIONS,
      showIf: "['Vendor Services', 'Internal Members'].includes(data.ServicesAndProviders)",
    },
    {
      name: 'BranchCategory',
      label: 'Branch/Category',
      type: 'Enum',
      options: BRANCH_CATEGORY_OPTIONS,
      showIf: "data.ServicesAndProviders === 'Law Enforcement Agency'",
    },
    {
      name: 'Job',
      label: 'Job',
      type: 'Enum',
      optionsSourceField: 'BranchCategory',
      optionsByValue: BRANCH_TO_JOB_OPTIONS,
      showIf: "Boolean(data.BranchCategory)",
    },
    { name: 'contact_info_break', label: 'Contact Info', type: 'PageBreak' },
    { name: 'Mobile', label: 'Mobile', type: 'Phone' },
    { name: 'Email', label: 'Email', type: 'Email' },
    {
      name: 'HomePhone',
      label: 'Home Phone',
      type: 'Phone',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    {
      name: 'HomeAddress',
      label: 'Home Address',
      type: 'Address',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    {
      name: 'City',
      label: 'City',
      type: 'Text',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    {
      name: 'State',
      label: 'State',
      type: 'Text',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    {
      name: 'ZipCode',
      label: 'Zip Code',
      type: 'Number',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    { name: 'professional_break', label: 'Professional Profile', type: 'PageBreak' },
    {
      name: 'CompanyName',
      label: 'Company Name',
      type: 'Text',
      showIf: "data.ServicesAndProviders !== 'Clients'",
    },
    {
      name: 'Title_Tagline',
      label: 'Title/Tagline',
      type: 'Text',
      showIf: "data.ServicesAndProviders !== 'Clients'",
    },
    {
      name: 'BusinessPhone',
      label: 'Business Phone',
      type: 'Phone',
      showIf: "data.ServicesAndProviders !== 'Clients'",
    },
    {
      name: 'OfficeEmail',
      label: 'Office Email',
      type: 'Email',
      showIf: "data.ServicesAndProviders !== 'Clients'",
    },
    {
      name: 'BusinessStreetAddress',
      label: 'Business Street Address',
      type: 'Address',
      showIf: "data.ServicesAndProviders !== 'Clients'",
    },
    { name: 'notes_break', label: 'Notes', type: 'PageBreak' },
    {
      name: 'Rating',
      label: 'Rating',
      type: 'Enum',
      options: ['1', '2', '3', '4', '5'],
    },
    {
      name: 'AdditionalInfo',
      label: 'Additional Info',
      type: 'LongText',
    },
    {
      name: 'notes',
      label: 'Private Notes',
      type: 'LongText',
    },
  ],
};

