import { TableDefinition } from '../types';

// Canonical ContactsDirectory schema (normalized from AppSheet export).
// Enum fields slice from EnumsCatalog by EnumCategory and display DisplayName.
// Stored value defaults to EnumValue unless enumValueSource is explicitly set to uniqueId/displayName.
export const CONTACTS_DIRECTORY_TABLE_DEF: TableDefinition = {
  id: 'contacts',
  name: 'Contacts Directory',
  keyField: 'id',
  labelField: 'name',
  schema: [
    { name: 'Client_ID', label: 'Client ID', type: 'Text', hidden: true, readOnly: true },
    { name: 'ContactID', label: 'Contact ID', type: 'Text', hidden: true, readOnly: true },

    { name: 'about_break', label: 'About', type: 'PageBreak' },
    { name: 'FirstName', label: 'First Name', type: 'Name' },
    { name: 'LastName', label: 'Last Name', type: 'Name' },
    { name: 'Photo', label: 'Photo', type: 'Image' },
    {
      name: 'EntityKind',
      label: 'Entity Type',
      type: 'Enum',
      enumCategory: 'EntityKind',
      enumCategoryAliases: ['EntityType', 'Entity Type'],
      enumValueSource: 'displayName',
      options: ['Person', 'Company', 'Team', 'Robot'],
      description: 'Select what kind of contact profile this is.',
    },
    {
      name: 'ServicesAndProviders',
      label: 'Service and Providers',
      type: 'Enum',
      enumCategory: 'ServicesAndProviders',
      enumCategoryAliases: ['ServiceAndProviders', 'Services and Providers', 'Services & Providers'],
      enumValueSource: 'displayName',
      options: [
        'Clients',
        'Broker / Lender / Closing Services',
        'Vendor Services',
        'Law Enforcement Agency',
        'Internal Members',
        'Rental Building',
      ],
      description: 'Choose the role group to show the right form sections.',
    },
    {
      name: 'ProRoleType',
      label: 'Transaction Services',
      type: 'Enum',
      enumCategory: 'ProRoleType',
      enumCategoryAliases: ['TransactionServices', 'Pro Role Type', 'Transaction Services', 'TransactionalServices', 'Transaction_Services', 'ProRole_Type'],
      enumValueSource: 'displayName',
      description: 'Select transaction-focused services for this contact.',
      showIf: "['Broker_Lender_Closing_Services', 'Broker / Lender / Closing Services', 'Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)",
    },
    {
      name: 'VendorRole',
      label: 'Vendor Services',
      type: 'Enum',
      enumCategory: 'VendorRole',
      enumCategoryAliases: ['VendorServices', 'Vendor Role', 'Vendor Services', 'Vendor_Service', 'Vendor_Services', 'VendorRoleType'],
      enumValueSource: 'displayName',
      description: 'Select vendor services this contact provides.',
      showIf: "['Vendor_Services', 'Vendor Services', 'Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders) && (ui.viewType === 'Form' || Boolean(data.VendorRole))",
    },
    {
      name: 'BranchCategory',
      label: 'Branch',
      type: 'Enum',
      enumCategory: 'Branch_Category',
      enumCategoryAliases: ['LawEnforcementBranch', 'Branch', 'Law Enforcement Branch', 'LawEnforcementAgencyBranch'],
      enumValueSource: 'displayName',
      options: ['Military', 'Police', 'Sheriff', 'Fire', 'Federal'],
      description: 'Choose the law enforcement branch first.',
      showIf: "['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)",
    },
    {
      name: 'Job',
      label: 'Category',
      type: 'Enum',
      optionsCategorySourceField: 'BranchCategory',
      enumValueSource: 'displayName',
      options: ['Army', 'Navy', 'Air Force', 'Marines', 'Coast Guard', 'Space Force', 'Patrol', 'Investigations', 'K-9', 'Traffic', 'Civil', 'Detention', 'Court Security', 'Operations', 'Prevention', 'Inspection', 'EMS', 'FBI', 'DEA', 'ATF', 'Homeland Security'],
      optionsByCategory: {
        Military: ['Army', 'Navy', 'Air Force', 'Marines', 'Coast Guard', 'Space Force'],
        Police: ['Patrol', 'Investigations', 'K-9', 'Traffic'],
        Sheriff: ['Patrol', 'Civil', 'Detention', 'Court Security'],
        Fire: ['Operations', 'Prevention', 'Inspection', 'EMS'],
        Federal: ['FBI', 'DEA', 'ATF', 'Homeland Security'],
      },
      description: 'Category options are filtered by the selected branch.',
      showIf: "['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders) && Boolean(data.BranchCategory)",
    },

    { name: 'my_home_break', label: 'My Home', type: 'PageBreak', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'HomePhone', label: 'Home Phone', type: 'Phone', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'HomeAddress', label: 'Home Address', type: 'Address', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'City', label: 'City', type: 'Text', showIf: "data.ServicesAndProviders === 'Clients'" },
    { name: 'County', label: 'County', type: 'Text', showIf: "data.ServicesAndProviders === 'Clients'" },
    {
      name: 'State',
      label: 'State',
      type: 'Enum',
      enumCategory: 'State',
      enumCategoryAliases: ['States', 'USState', 'BusinessState', 'StateList'],
      enumValueSource: 'displayName',
      options: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      showIf: "data.ServicesAndProviders === 'Clients'",
    },
    {
      name: 'ZipCode',
      label: 'Zip Code',
      type: 'Text',
      placeholder: '90210',
      description: '5-digit zip code.',
      showIf: "data.ServicesAndProviders === 'Clients'",
    },

    { name: 'contact_info_break', label: 'Contact Info', type: 'PageBreak' },
    { name: 'Mobile', label: 'Mobile', type: 'Phone', placeholder: '(555) 123-4567', description: 'US format: (555) 123-4567' },
    { name: 'Email', label: 'Contact Email', type: 'Email', placeholder: 'myname@email.com', description: 'Use a valid email like myname@email.com' },

    { name: 'professional_break', label: 'Professional Profile', type: 'PageBreak', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'CompanyName', label: 'Company Name', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'Title_Tagline', label: 'Title / Tagline', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'TeamName', label: 'Team Name', type: 'Text', showIf: "data.EntityKind === 'Team'" },
    { name: 'BrokerLicense', label: 'Broker License', type: 'Text', showIf: "['Internal_Members', 'Internal Members', 'Broker_Lender_Closing_Services', 'Broker / Lender / Closing Services', 'Vendor_Services', 'Vendor Services', 'Rental_Building', 'Rental Building'].includes(data.ServicesAndProviders)" },
    { name: 'ContactLicense', label: 'Contact License', type: 'Text', showIf: "['Internal_Members', 'Internal Members', 'Broker_Lender_Closing_Services', 'Broker / Lender / Closing Services', 'Vendor_Services', 'Vendor Services', 'Rental_Building', 'Rental Building'].includes(data.ServicesAndProviders)" },
    { name: 'BusinessPhone', label: 'Business Phone', type: 'Phone', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'OfficeEmail', label: 'Office Email', type: 'Email', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'BusinessStreetAddress', label: 'Business Street Address', type: 'Address', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    { name: 'BusinessCity', label: 'Business City', type: 'Text', showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'" },
    {
      name: 'BusinessState',
      label: 'Business State',
      type: 'Enum',
      enumCategory: 'State',
      enumCategoryAliases: ['States', 'USState', 'BusinessState', 'StateList', 'State_Province'],
      enumValueSource: 'displayName',
      options: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'",
    },
    {
      name: 'BusinessZipCode',
      label: 'Business Zip Code',
      type: 'Text',
      placeholder: '90210',
      description: '5-digit zip code.',
      showIf: "!data.ServicesAndProviders || data.ServicesAndProviders !== 'Clients'",
    },

    { name: 'social_break', label: 'Website and Social', type: 'PageBreak', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)" },
    { name: 'WebsiteURL', label: 'Website URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your website homepage URL.' },
    { name: 'ProfileURL', label: 'Profile URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Primary public profile URL for this contact.' },
    { name: 'YouTube', label: 'YouTube', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your YouTube channel URL.' },
    { name: 'YouTubeThumbnail', label: 'YouTube Thumbnail', type: 'Image', showIf: "ui.touched.YouTube || ui.activeField === 'YouTube' || Boolean(data.YouTube)" },
    { name: 'YouTubePlayer', label: 'YouTube Player', type: 'App', showIf: 'Boolean(data.YouTube)' },
    { name: 'ShareWith', label: 'Share With', type: 'Email', hidden: true },
    { name: 'LinkedInURL', label: 'LinkedIn URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your LinkedIn profile URL.' },
    { name: 'FacebookURL', label: 'Facebook URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your Facebook page URL.' },
    { name: 'InstagramURL', label: 'Instagram URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your Instagram profile URL.' },
    { name: 'WhatsAppURL', label: 'WhatsApp URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Use a full WhatsApp link such as https://wa.me/15551234567.' },
    { name: 'TikTokURL', label: 'TikTok URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your TikTok profile URL.' },
    { name: 'X_URL', label: 'X URL', type: 'Url', showIf: "!['Law_Enforcement_Agency', 'Law Enforcement Agency'].includes(data.ServicesAndProviders)", description: 'Your X profile URL.' },
    { name: 'OwnerEmail', label: 'Owner Email', type: 'Email', hidden: true, readOnly: true },

    { name: 'notes_break', label: 'Notes', type: 'PageBreak' },
    { name: 'Rating', label: 'Rating', type: 'Enum', enumCategory: 'Rating', enumCategoryAliases: ['ContactRating'], enumValueSource: 'displayName', options: ['1', '2', '3', '4', '5'] },
    {
      name: 'AI_ResponseMode',
      label: 'AI Response Mode',
      type: 'Enum',
      enumCategory: 'AI_ResponseMode',
      enumCategoryAliases: ['AIResponseMode', 'Ai Response Mode'],
      enumValueSource: 'displayName',
      options: ['Balanced', 'Concise', 'Detailed'],
    },
    {
      name: 'Tags',
      label: 'Tags',
      type: 'EnumList',
      enumCategory: 'TagList',
      enumCategoryAliases: ['Tags', 'ContactTags'],
      enumValueSource: 'displayName',
      description: 'Short labels used to categorize or quickly filter contacts.',
    },
    { name: 'AdditionalInfo', label: 'Additional Info', type: 'LongText', description: 'General notes about the contact that may be useful to others on the team.' },
    { name: 'notes', label: 'Private Notes', type: 'LongText', description: 'Internal notes visible only to you or restricted users.' },

    { name: 'security_break', label: 'Account and Security', type: 'PageBreak', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },
    { name: 'SecurityLevel', label: 'Security Level', type: 'Number', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },
    { name: 'AddedBy', label: 'Added By', type: 'Email', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },
    { name: 'AppUserRef', label: 'App User', type: 'Ref', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },
    { name: 'DateAdded', label: 'Date Added', type: 'DateTime', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },
    { name: 'TenantID', label: 'Tenant ID', type: 'Text', showIf: "['Internal_Members', 'Internal Members'].includes(data.ServicesAndProviders)" },

    // Virtual/computed style fields kept hidden for future backend parity.
    { name: 'FullName', label: 'Full Name (Computed)', type: 'Text', hidden: true },
    { name: 'ComputedAddress', label: 'Computed Address', type: 'Address', hidden: true },
    { name: 'Avatar', label: 'Avatar', type: 'Thumbnail', hidden: true },
    { name: 'EntryProfile', label: 'Entry Profile', type: 'Text', hidden: true },
  ],
};

